credentials:
  usernames:
    mykitchen:
      name: My Kitchen
      password: abc123  # Use hashed password in production!
      role: kitchen
    myngo:
      name: Helping Hands NGO
      password: ngo123
      role: ngo

cookie:
  expiry_days: 1
  key: some_random_key
  name: smart_food_auth

preauthorized:
  emails: []

